### ISSUE TITLE
Review App

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/frontend#10]
- [x] netifly?
- [x] staging server CORS domain whitelist

**Comment by yoyo930021** [comment]
netifly Deploy Previews
#13

**Comment by Yukaii** [comment]
@stegben 需要支援 CORS domain whitelist 💪  

domain 的規則是 `https://*.netlify.app/`

**Comment by Yukaii** [comment]
Thanks @stegben @yoyo930021 🎉
