### ISSUE TITLE
Top nav 常見問題 連結錯誤

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/frontend#107]
應該連到 https://about.disfactory.tw/#faq

**Comment by Yukaii** [comment]
@yeefun 這個連結好像也沒辦法 scroll 到常見問題的部分~~

**Comment by yeefun** [comment]
about page 沒有做 anchor，我這邊要再改

**Comment by Yukaii** [comment]
https://github.com/Disfactory/about.disfactory.tw/issues/80

**Comment by Yukaii** [comment]
resolved in #147
