### ISSUE TITLE
案件資訊呈現followup當中的文字

### ISSUE THREAD

**Issue by deeper747** [Disfactory/frontend#128]
**Is your feature request related to a problem? Please describe.**
有許多人看到簡化的資訊不知如何判讀，會再打電話到地球公民詢問，花地公工作人員不少時間。

**Describe the solution you'd like**
呈現db中該案件的「Follow ups」純文字內容給他們

**Describe alternatives you've considered**
改標籤到更清楚

**Additional context**
還需要開api、檢查一遍followup的格式和內容、設計呈現方式

**Comment by deeper747** [comment]
在document的table當中新增一個 followups4user

在factory的table當中新增一個抓取相關 document > followups4user 欄位，並合併起來的欄位

地球公民會再逐案過一遍所有的描述，綜合followups的內容，寫在followups4user中

**Comment by deeper747** [comment]
會在factory api新增的欄位

```
  "follow_ups_for_user": [
    {
        "note": "Follow up for Users 222222",
        "created_at": "2021-10-13 11:22:47"
    },
    {
        "note": "Follow up for Users 333333 # 2021-10-12",
        "created_at": "2021-10-13 11:22:47"
    },
  ]
```

**Comment by Yukaii** [comment]
- [ ] 需要先檢查後臺這個欄位有沒有隱私資訊或聯絡人資料

**Comment by peii052** [comment]
舉例：

**政府回函              |       日期       |  經勘查/排程勘查  |  勘查結果**
彰化縣政府回函   | 2021/12/15  |          已勘查          |  非工廠違規(農設/倉儲/未達工廠規模)

**Comment by aelcenganda** [comment]
我這邊想提出一個考慮，就是手機版可能空間不夠，不能一行顯示一筆回覆紀錄，會變成兩行。想問 @peii052 如果會斷行，怎樣紀錄比較方便和清楚？

**Comment by aelcenganda** [comment]
試試看堆疊這個格式：

20211215彰化縣政府回函
已勘查_該工廠非工廠違規(農舍/倉儲/未達工廠規模)

20211120彰化縣政府回函
已勘查_該工廠非工廠違規(農舍/倉儲/未達工廠規模)

20211026彰化縣政府回函
已勘查_該工廠非工廠違規(農舍/倉儲/未達工廠規模)

**Comment by DoraLyn20** [comment]
已更新[設計圖](https://www.figma.com/file/dFuJKpdDcmHNDqdj1011Zo/Disfactory_UI_design_2021?node-id=2097%3A8774)。

![image](https://user-images.githubusercontent.com/63245687/147049622-2800e38b-3c6a-49b2-90a9-e0e27d699837.png)


若行而有餘力，可以許願順便把Pin的selected status做起來嗎？可參考 [Design system](https://www.figma.com/file/dFuJKpdDcmHNDqdj1011Zo/Disfactory_UI_design_2021?node-id=362%3A3921) 裡的元件，以下也附上截圖。
![image](https://user-images.githubusercontent.com/63245687/147049502-f23af455-4c6e-4d13-83f8-584a697edb75.png)

**Comment by Yukaii** [comment]
API ready, `follow_ups_for_user` 欄位已經可以在 staging 存取，可以實作~~
