### ISSUE TITLE
Clustered factories should be broken out when zoom level is high

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/frontend#144]
**Describe the bug**
請清晰詳細的描述這個問題

**To Reproduce**
列出可以重現問題的步驟：

**Expected behavior**

**Screenshots**
截圖

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdon** [comment]
duplicate of #150 ?

**Comment by Yukaii** [comment]
> duplicate of #150 ?

you're right
