### ISSUE TITLE
點「常見問題」會自動跳轉到landing page的「教學頁面」，而不是「常見問題」

### ISSUE THREAD

**Issue by DoraLyn20** [Disfactory/frontend#147]
**Describe the bug**
點「常見問題」會自動跳轉到landing page的「教學頁面」，而不是「常見問題」

**To Reproduce**
列出可以重現問題的步驟：
1. 點disfactory.tw裡面的「常見問題」

**Expected behavior**
希望可以直接自動下滑到 about.disfactory.tw 的常見問題

**Screenshots**
直接跳到網頁的這個部分
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/63245687/162290612-a50d824d-653a-4138-9038-7411bc93dd56.png">

**Comment by Yukaii** [comment]
dupliate of https://github.com/Disfactory/frontend/issues/107
