### ISSUE TITLE
UI 2.0 安全須知

### ISSUE THREAD

**Issue by deeper747** [Disfactory/frontend#25]
**Describe the bug**
安全須知目前沒有資訊

**Expected behavior**
如第一版運作

**Screenshots**
![IMG_9455](https://user-images.githubusercontent.com/60970217/94098242-cbec6380-fe5a-11ea-882f-0db4923c0b8c.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - iphone7
 - iOS13.7
 - safari

**Comment by Yukaii** [comment]
改用 https://vuetifyjs.com/en/components/carousels/#carousels 元件來做

**Comment by aelcenganda** [comment]
應該是 scrolling 出問題

**Comment by Yukaii** [comment]
Fixed in 1af6dbe3486d8bc5dd3a3d5658e88eafd208c239
