### ISSUE TITLE
分享連結複製的網址應該是工廠經緯度而不是地圖中心畫面

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/frontend#34]

**Comment by DoraLyn20** [comment]
![image](https://user-images.githubusercontent.com/63245687/95336342-279b0000-08e3-11eb-9d5d-218b1edab475.png)

![image](https://user-images.githubusercontent.com/63245687/95336589-6df05f00-08e3-11eb-97b7-8ed32782e0c3.png)
