### ISSUE TITLE
初始popup內容、排版

### ISSUE THREAD

**Issue by deeper747** [Disfactory/frontend#40]
@aelcenganda 昨天跟我說到初始popup沒有把「新增建工廠」放在最優先的位置，排版也有些怪

<img src="https://user-images.githubusercontent.com/60970217/97538046-bd194380-19fa-11eb-8723-930e34cfaf50.jpg" alt="disfactory說明popup" width="450">

我重新看了一下，嘗試自己做了些微調整
<img src="https://user-images.githubusercontent.com/60970217/97538060-c1ddf780-19fa-11eb-9181-b3dbd35a4b2a.jpg" alt="disfactory說明popup2" width="450">

1.文案變成：
歡迎來到農地違章工廠回報系統！

需要大家回報以下工廠之照片及資訊：
 - 2016.05.20後新增的農地違章工廠
 - 中高污染工廠

以上資訊將由地球公民基金會彙整後，向政府舉報並追蹤拆除進度。

2.把第一句話變成置中
3.幫一些重點詞彙加上粗體

看 @Oriyar @JennyLan 有沒有什麼意見～

**Comment by Yukaii** [comment]
修改這個檔案

https://github.com/Disfactory/frontend/blob/56f7e1f47cfb50ddd07ff5f6ad19be9a87acd03a/src/components/GettingStartedModal.vue#L5-L13
