### ISSUE TITLE
pin預設值改成「疑似」

### ISSUE THREAD

**Issue by deeper747** [Disfactory/frontend#51]
**Describe the bug**
pin的預設值現在是「已檢舉」

**Expected behavior**
新增一個狀態為「疑似」，並將預設值改成它。

**Comment by aelcenganda** [comment]
就是前端撈不到 `display_status` 的時候，該 factory ID 的 pin 要設為`疑似`。

@JennyLan 需要你再幫忙出這個 pin 的顏色，這個顏色會是地圖上的主要顏色，目前五萬多筆尚未檢舉的資料都會是這個顏色。

**Comment by JennyLan** [comment]
“疑似”用這個顏色：#D27E00

**Comment by Yukaii** [comment]
Fixed in 88c2879
