### ISSUE TITLE
指北鈕在 Firefox 上壞掉了

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/frontend#62]
指北按鈕歸零按下去後不會正北朝上

*To Reproduce*
1. 雙指縮放旋轉
2. 按下指北鈕

版本：
Firefox 28.2
iOS 14.2

Note:
fine on Chrome, Safari and Edge on iOS

![signal-2020-12-30-191933_002](https://user-images.githubusercontent.com/9480974/103348727-d95a5f00-4ad5-11eb-823d-6a097aa69ee9.jpeg)
![signal-2020-12-30-191933_003](https://user-images.githubusercontent.com/9480974/103348729-dc554f80-4ad5-11eb-9cff-ac3b32a21513.jpeg)
![signal-2020-12-30-191933_004](https://user-images.githubusercontent.com/9480974/103348733-dd867c80-4ad5-11eb-8c8a-4e0e9fe630e0.jpeg)

**Comment by Yukaii** [comment]
GA 使用者佔 1.43%，暫時不會修

**Comment by Yukaii** [comment]
Should be fixed in newer version of iOS
