### ISSUE TITLE
有辦法讓有發出公文的 pin 不要被擋住嗎？

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/frontend#63]
不容易看到有被檢舉的工廠

<img alt="signal-2021-12-30-195850" width="300" src="https://user-images.githubusercontent.com/9480974/103349990-87b3d380-4ad9-11eb-9745-0235329b599a.jpeg">

**Comment by Yukaii** [comment]
### Sol:

https://github.com/Disfactory/frontend/blob/88c2879c143185a1cfbf05810a58dd0018e87933/src/lib/map.ts#L66-L75

Style 加上 zIndex 來區隔不同工廠狀態
