### ISSUE TITLE
四塊均需 hover message

### ISSUE THREAD

**Issue by jidanni** [Disfactory/frontend#77]
如 "T" 不敢按，因不知是什麼功能。
![3453-0](https://user-images.githubusercontent.com/1230959/84601597-eefa9500-aeb3-11ea-86df-f22e9c946a70.jpg)
故四塊均需 hoverover message saying what they do, e.g., 放大，縮小…

**Comment by Yukaii** [comment]
考慮使用 Vuetify 按鈕的 Tooltip 元件 https://vuetifyjs.com/en/components/tooltips/#usage

**Comment by Yukaii** [comment]
- [ ] 各個按鈕加上 title attribute
- [ ] 確定 attribute 為中文

**Comment by Yukaii** [comment]
Assign to @komali2

**Comment by komali2** [comment]
This was potentially fixed upstream by OM, not sure, in any case, there's a title attribute now, and hover works.

However, it's in English, so I'll submit a PR or at least issue to OM to allow insertion of a custom string, so translated strings can be used.

**Comment by komali2** [comment]
oh snap https://github.com/openlayers/openlayers/blob/main/src/ol/control/Zoom.js#L70 the feature already exists!

**Comment by komali2** [comment]
We'll change it to mandarin at least for now
