### ISSUE TITLE
經濟部資料整合、首頁 UI 修整

### ISSUE THREAD

**Issue by wutingy** [Disfactory/frontend#90]
# 狀態 UI 修改
- 改成狀態：未處理、處理中、已斷電、已拆除（四個顏色）
https://www.figma.com/proto/dFuJKpdDcmHNDqdj1011Zo/Disfactory_UI_design_2021?node-id=2097%3A17786&scaling=min-zoom
https://www.figma.com/proto/dFuJKpdDcmHNDqdj1011Zo/Disfactory_UI_design_2021?node-id=2097%3A11348&scaling=min-zoom
- 使用行為改成：類似 checkbox 的行為，預設是全部 check (active)，如果有點 button，就變成 un-check (un-active)
- 顯示設定按鈕與旁邊切換狀態的按鈕區別開

# 經濟部資料整合
https://www.figma.com/proto/dFuJKpdDcmHNDqdj1011Zo/Disfactory_UI_design_2021?node-id=2097%3A17637&scaling=min-zoom
新增欄位：資料來源：`經濟部`、`農委會`、`本系統`

**Comment by aelcenganda** [comment]
https://github.com/Disfactory/frontend/issues/89

**Comment by aelcenganda** [comment]
後端欄位修改的討論，以這份為準

https://github.com/Disfactory/Disfactory/issues/482

**Comment by deeper747** [comment]
> 未處理 = 疑似工廠
> 處理中 = 已檢舉 + 已排程稽查 + 陳述意見期 + 已勒令停工
> 已斷電 = 已發函斷電 + 已排程拆除
> 已拆除 = 已拆除

然後我剛剛細看之後，決定新增一個，要不然「不再追蹤」塞不進任何一個標籤～

> 無法處理 = 不再追蹤

**Comment by wutingy** [comment]
https://www.figma.com/proto/dFuJKpdDcmHNDqdj1011Zo/Disfactory_UI_design_2021?node-id=2097%3A17786&scaling=min-zoom&page-id=2097%3A8774
補一個「無法處理」的 tag
